# Generated by Django 3.1.7 on 2021-05-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pons_position', models.JSONField(blank=True, null=True)),
                ('pons_details', models.JSONField(default=game.models.generate_pons_details)),
                ('toggle_board', models.BooleanField(default=False)),
                ('pon_status', models.JSONField(default=game.models.generate_pon_status)),
                ('turn', models.CharField(default='black', max_length=5)),
                ('player_black', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_black', to=settings.AUTH_USER_MODEL)),
                ('player_white', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_white', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
