# Generated by Django 3.1.7 on 2021-05-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210523_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='toggle_board',
        ),
    ]
