# Generated by Django 3.1.7 on 2021-05-25 11:43

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_game_toggle_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='king_positions',
            field=models.JSONField(default=game.models.generate_king_positions),
        ),
    ]
