# Generated by Django 3.1.7 on 2021-05-25 12:26

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_king_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moved_checks',
            field=models.JSONField(default=game.models.generate_moved_checks),
        ),
    ]
