# Generated by Django 3.1.7 on 2021-05-25 13:24

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_moved_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moves',
            field=models.JSONField(default=game.models.generate_moves),
        ),
    ]
